exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex("flavors")
    .del()
    .then(function() {
      // Inserts seed entries
      return knex("flavors").insert([
        { name: "Ammonia", description: "N/A" },
        { name: "Anise", description: "N/A" },
        { name: "Apple", description: "N/A" },
        { name: "Apricot", description: "N/A" },
        { name: "Banana", description: "N/A" },
        { name: "Berry", description: "N/A" },
        { name: "Bitter", description: "N/A" },
        { name: "Blue Cheese", description: "N/A" },
        { name: "Blueberry", description: "N/A" },
        { name: "Buttery", description: "N/A" },
        { name: "Cheese", description: "N/A" },
        { name: "Chemical", description: "N/A" },
        { name: "Cherry", description: "N/A" },
        { name: "Chestnut", description: "N/A" },
        { name: "Chocolate", description: "N/A" },
        { name: "Citrusy", description: "N/A" },
        { name: "Coffee", description: "N/A" },
        { name: "Dank", description: "N/A" },
        { name: "Diesel", description: "N/A" },
        { name: "Dill", description: "N/A" },
        { name: "Earthy", description: "N/A" },
        { name: "Flowery", description: "N/A" },
        { name: "Fruity", description: "N/A" },
        { name: "Grape", description: "N/A" },
        { name: "Grapefruit", description: "N/A" },
        { name: "Harsh", description: "N/A" },
        { name: "Haze", description: "N/A" },
        { name: "Herbal", description: "N/A" },
        { name: "Honey", description: "N/A" },
        { name: "Kush", description: "N/A" },
        { name: "Lavender", description: "N/A" },
        { name: "Lemony", description: "N/A" },
        { name: "Lime", description: "N/A" },
        { name: "Mango", description: "N/A" },
        { name: "Melon", description: "N/A" },
        { name: "Menthol", description: "N/A" },
        { name: "Minty", description: "N/A" },
        { name: "Musky", description: "N/A" },
        { name: "Orange", description: "N/A" },
        { name: "Peach", description: "N/A" },
        { name: "Pear", description: "N/A" },
        { name: "Peppery", description: "N/A" },
        { name: "Pine", description: "N/A" },
        { name: "Pine Berry", description: "N/A" },
        { name: "Pineapple", description: "N/A" },
        { name: "Piney", description: "N/A" },
        { name: "Pungent", description: "N/A" },
        { name: "Sage", description: "N/A" },
        { name: "Skunky", description: "N/A" },
        { name: "Smooth", description: "N/A" },
        { name: "Sour", description: "N/A" },
        { name: "Spicy", description: "N/A" },
        { name: "Strawberry", description: "N/A" },
        { name: "Sweet", description: "N/A" },
        { name: "Tangy", description: "N/A" },
        { name: "Tar", description: "N/A" },
        { name: "Tea", description: "N/A" },
        { name: "Tree Fruit", description: "N/A" },
        { name: "Tropical", description: "N/A" },
        { name: "Vanilla", description: "N/A" },
        { name: "Violet", description: "N/A" },
        { name: "Wild Garlic", description: "N/A" },
        { name: "Woody", description: "N/A" }
      ]);
    });
};
